2 create postgresql terraform module
opsd-io/terraform-module-digitalocean-postgresql pull request #3
Opened 2024-03-20 14:16 UTC by jakub-kubera

## What changes does your PR bring?

In a few words, describe what changes your commits make to the code.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (non-breaking change to the build process or auxiliary tools)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Documentation (Improvements or additions to documentation)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)

## References

Fixes:

# Checklist:

- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented on my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [x ] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing unit tests pass locally with my changes
- [ x] Any dependent changes have been merged and published in downstream modules

2024-03-25 11:25 UTC, stawii requested changes

2024-03-25 11:25 UTC, stawii commented on README.md
> +module "terraform-module-digitalocean-mysql" {
replace name with "example" or "db1" or something more "exemplary".

2024-03-25 11:25 UTC, stawii commented on README.md
> +  postgresql_main_size       = "db-s-1vcpu-1gb"
Fix spacing to similar what `terraform fmt` does. Remove the "variables" comment.

2024-03-25 11:25 UTC, stawii commented on examples/create_postgresql_database/.tool-versions
The `asdf` takes  configs from parent dirs too. It's save to remove this file - it's is the same as in root.

2024-03-25 11:25 UTC, stawii commented on examples/create_postgresql_database/main.tf
> +module "Digitalocean_postgresql" {
replace name with "example" or "db1" or something more "exemplary".

2024-03-25 11:25 UTC, stawii commented on examples/create_postgresql_database/main.tf
> +  engine                     = "pg"
What happens if I put `redis` here? I guess this variable is redundant if we have per-engine modules.

2024-03-25 11:25 UTC, stawii commented on main.tf
> +#Description : adding database firewall rules.
Drop this comment.

2024-03-25 11:25 UTC, stawii commented on main.tf
> +#Description : adding users to database.
Drop this comment.

2024-03-25 11:25 UTC, stawii commented on main.tf
> +#Description : creating main database.
Drop this comment.

2024-03-25 11:25 UTC, stawii commented on main.tf
> +resource "digitalocean_database_cluster" "postgresql_main" {
Fix name to `postgresql` just to point out we're doing postgres engine here, or generic `main` for short.

2024-03-25 11:25 UTC, stawii commented on main.tf
> +resource "digitalocean_database_user" "user_creation" {
Fix name to `main`.

2024-03-25 11:25 UTC, stawii commented on main.tf
> +resource "digitalocean_database_firewall" "firewall" {
Fix name to `main`.

2024-03-25 11:25 UTC, stawii commented on main.tf
> +  engine     = var.engine
It's is postgres only module, maybe it's better to hardcode "pg" here?

2024-03-25 11:25 UTC, stawii commented on outputs.tf
> +output "postgresql_main_host_id" {
Drop `postgresql_main_` prefix from all outputs.

2024-03-25 11:25 UTC, stawii commented on outputs.tf
> +output "database_firewall_id" {
Change to `firewall_id`.

2024-03-25 11:25 UTC, stawii commented on outputs.tf
> +output "database_users_id" {
Change to `user_ids`. Plurals are better with (s).

2024-03-25 11:25 UTC, stawii commented on variables.tf
> +variable "postgresql_main_node_count" {
Why not node_count?

2024-03-25 11:25 UTC, stawii commented on variables.tf
> +variable "databasename" {
Either just `name` or `cluster_name`.

2024-03-25 11:25 UTC, stawii commented on variables.tf
> +variable "engine" {
It is postgres module, what if I use "redis" here? Saver and better to hardcode this variable in resource call.

2024-03-25 11:25 UTC, stawii commented on variables.tf
> +variable "postgresql_main_size" {
Either `node_size` - to match with `node_count`, `droplet_size` to explain meaning, or just `size` as it is in resource. I think `node_size` is best.

2024-03-25 11:25 UTC, stawii commented on variables.tf
> +variable "version_of_engine" {
Hm.. why not `engine_version`? Maybe `postgresql_version`? We cannot use just `version` because it's not valid identifier.

2024-03-25 11:25 UTC, stawii commented on versions.tf
> +      version = "2.34.1"
Don't pin version in module.

2024-03-25 11:25 UTC, stawii commented on variables.tf
> +variable "firewall_rules" {
Order: description, type, default.

2024-03-25 11:25 UTC, stawii commented on variables.tf
> +variable "database_users" {
Order: description, type, default.

2024-03-25 12:10 UTC, jakub-kubera reviewed
changes implmented

2024-03-25 12:14 UTC, jakub-kubera reviewed
implemented changes

2024-03-26 11:26 UTC, michaltomczuk approved these changes
LGTM

2024-03-26 11:30 UTC, merged